### ISSUE TITLE
Concourse returns "file not found" when trying to use container to run shell commands

### ISSUE THREAD

**Issue by lockan** [rafikn/flowdock-notification-resource#7]
**Use case:** 
For StuffNz: invoke Rex (hubot) via a curl command to the flowdock private message api. 

**Problem:**
When using the image in a concourse task definition, concourse returns "File not found" when trying to invoke any shell command ("echo", "ls", etc.). A bare-bones hello-world task configuration does the same. 
Using the base images instead of this resource (golang:alpine or alpine:edge) will work as expected (for "ls" or "echo", but not "curl" since that's not installed on those images). 

**Sample pipeline for testing:**

```
resources:
- name: flowdock-notification
  type: docker-image
  source:
     repository: ((flowdock-notification-url))
    tag: latest
- name: golang-alpine
  type: docker-image
  source:
    repository: golang
    tag: alpine
- name: flowdock
  type: flowdock-notification
  source:
    author: ((arbitrary-author-name))
    avatar: ((some-image-url))
    flow_api: https://api.flowdock.com/messages
    flow_token: ((some-valid-flow-token)
    thread_id: ((some-arbitrary-thread-id))
jobs:
- name: test-curl-rex
  public: true
  serial: true
  plan:
  - aggregate:
    - get: golang-alpine
    - get: flowdock
  - task: this-will-succeed
    image: golang-alpine
    config:
      platform: linux
      run:
        path: /bin/sh
        args:
          - -exc
          - |
          - echo "Hello world"
  - task: this-will-fail
    image: flowdock
    config:
      platform: linux
      run:
        path: /bin/sh
        args:
          - -exc
          - |
          - echo "Goodbye world"
```
